name: Build MediaHelper

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build mediaHelper
      run: |
        msbuild mediaHelper.sln /p:Configuration=Release /p:Platform=x64
